spring:
  application:
    name: master-manager
  datasource:
    driverClassName: org.h2.Driver
    #url: jdbc:h2:mem;DB_CLOSE_DELAY=-1;DB_CLOSE_ON_EXIT=FALSE
    url: jdbc:h2:./master-manager-db
    username: sa
    password: admin
    platform: h2
  h2:
    console:
      enabled: true
      path: /console
      settings:
        trace: false
        web-allow-others: false
  jpa:
    database-platform: org.hibernate.dialect.H2Dialect
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        format_sql: false
        show_sql: false
        use_sql_comments: false
ssh:
  connection-timeout: 10000
edge:
  access:
    key-file-path: src/main/resources/edge
aws:
  initial-max-instances: 2
  max-retries: 10
  delay-between-retries: 5000
  connection-timeout: 180000
  access:
    key: AKIAS5UBHWDI3WO52EV5
    secret-key: ${secret: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}
    key-file-path: src/main/resources/aws/ec2.pem
    username: ubuntu
  instance:
    ami: ami-0b30a88613f4a9846
    security-group: us-manager-security-group
    key-pair: ec2
    type: t2.micro
    tag: us-manager
container:
  database:
    deploy-delay: 5000
  delay-before-stop: 45000
  migrate-container-on-event-count: 2
  monitor-period: 60000
  replicate-container-on-event-count: 2
  stop-container-on-event-count: 3
docker:
  install-script: docker-install.sh
  install-script-path: src/main/resources/scripts/docker-install.sh
  uninstall-script: docker-uninstall.sh
  uninstall-script-path: src/main/resources/scripts/docker-uninstall.sh
  api:
    port: 2376
  api-proxy:
    username: username
    password: password
    port: 2375
  hub:
    username: danielfct
  swarm:
    manager: ${dockerManager:daniel@dpimenta.ddns.net}
    max-workers: 1
eureka:
  port: 8761
prometheus:
  node-exporter:
    install-script: node-exporter-install.sh
    install-script-path: src/main/resources/scripts/node-exporter-install.sh
host:
  maximum-cpu-percentage: 90
  maximum-hosts: 0
  maximum-ram-percentage: 90
  minimum-hosts: 1
  monitor-period: 60000
  start-host-on-events-count: 3
  stop-host-on-events-count: 3
  local-machine-dns: dpimenta.ddns.net # from www.noip.com, to bypass router's dynamic ip
master-manager:
  mode: LOCAL
  monitor-period: 30000
  tests:
    test-logs-enable: ${testLogs:true}
nginx-load-balancer:
  api-url: /_/nginx-load-balancer-api/api
location-request:
  port: 1919
  minimum-request-count-percentage: 15.0
rules:
  service-rule-template-file: service-rule-template.drl
  host-rule-template-file: host-rule-template.drl
#debug: true
#trace: true
logging:
  config: file:src/main/resources/logging/logback-spring.xml
#  level:
#    org:
#      hibernate:
#        sql: DEBUG
#      type:
#        descriptor:
#          sql:
#            BasicBinder: TRACE